# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget aquila-engine vma imgui)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target aquila-engine
add_library(aquila-engine SHARED IMPORTED)

set_target_properties(aquila-engine PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLM_FORCE_DEPTH_ZERO_TO_ONE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/l/C++/Vulkan/AquilaEngine/aquila-engine/include"
  INTERFACE_LINK_LIBRARIES "SDL2::SDL2;vma;imgui"
)

# Create imported target vma
add_library(vma INTERFACE IMPORTED)

set_target_properties(vma PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/l/C++/Vulkan/AquilaEngine/aquila-engine/third-party/vma"
)

# Create imported target imgui
add_library(imgui SHARED IMPORTED)

set_target_properties(imgui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/l/C++/Vulkan/AquilaEngine/aquila-engine/third-party/imgui"
)

# Import target "aquila-engine" for configuration "Debug"
set_property(TARGET aquila-engine APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(aquila-engine PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/l/C++/Vulkan/AquilaEngine/aquila-engine/lib/libaquila-engine.so"
  IMPORTED_SONAME_DEBUG "libaquila-engine.so"
  )

# Import target "imgui" for configuration "Debug"
set_property(TARGET imgui APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(imgui PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "SDL2::SDL2"
  IMPORTED_LOCATION_DEBUG "/home/l/C++/Vulkan/AquilaEngine/aquila-engine/lib/libimgui.so"
  IMPORTED_SONAME_DEBUG "libimgui.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
